# Generated by Django 2.2.6 on 2019-10-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='diagosis',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='symptoms',
            field=models.TextField(max_length=1000),
        ),
    ]
