# Generated by Django 2.2.6 on 2019-10-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientrecord_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='diagosis',
            new_name='diagnosis',
        ),
    ]
